
---

- hosts: all
  tasks:
    - name: create venv
      command: python3 -m venv /home/ubuntu/jmstudios/backend/venv

    - name: create alias for python3
      command: alias python=python3

    - name: move to backend and pip install dependencies
      command: pip3 install -r requirements.txt
      args:
        chdir: jmstudios/backend
      become: true




- hosts: all
  vars:
    machine_ip: "{{ machine_ip }}"
    full_url: "{{ full_url }}"
  tasks:
    - name: send setup_data
      synchronize:
        src: ~/Documents/WebDevWorkspace/ReactPractice/ReactPractice/backend/db_setup_scripts/setup_data
        dest: "~/jmstudios/backend/db_setup_scripts/"

    - name: send .aws credentials
      synchronize: 
        src: ~/.aws
        dest: ~/ 

    - name: run python setup and initialize db
      command: python3 db_setup_scripts/db_setup.py
      async: 13000
      poll: 0
      args:
        chdir: jmstudios/backend




- hosts: all
  tasks:
    - name: create flask env for flask modules
      command: pip3 install -e .
      args:
        chdir: jmstudios/backend
      become: true

    - name: export FLASK_APP
      command: echo 'export FLASK_APP=jmstudios_backend' >> ~/.bash_profile

    - name: cd to proper location?
      shell: cd jmstudios/backend/jmstudios_backend

    - name: run uwsgi with port and log
      become: true
      comand:  uwsgi --http-socket 0.0.0.0:5050 --logto /tmp/uwsgi.log --wsgi-file jmstudios/backend/jmstudios_backend/wsgi.py &
      async: 15770000
      poll: 0
