
---

- hosts: all
  tasks:
    - name: create venv
      shell: python3 -m venv /home/ubuntu/jmstudios/backend/venv

    - name: create alias for python3
      shell: alias python=python3

    - name: move to backend and pip install dependencies
      shell: cd jmstudios/backend && pip3 install -r requirements.txt
      become: true




- hosts: all
  vars:
    machine_ip: "{{ machine_ip }}"
    full_url: "{{ full_url }}"
  tasks:
    - name: show me ip
      debug: 
        msg: "machine ip is {{ machine_ip }} full url is {{ full_url }}"

    - name: send setup_data
      synchronize:
        src: ~/Documents/WebDevWorkspace/ReactPractice/ReactPractice/backend/jmstudios_backend/db_setup_scripts/setup_data
        dest: "~/jmstudios/backend/jmstudios_backend/db_setup_scripts/"

    - name: send .aws credentials
      synchronize: 
        src: ~/.aws
        dest: ~/ 

    - name: run python setup and initialize db
      shell: python3 jmstudios/backend/jmstudios_backend/db_setup_scripts/db_setup.py




- hosts: all
  tasks:
    - name: create flask env for flask modules
      shell: cd jmstudios/backend && pip3 install -e .
      become: true

    - name: export FLASK_APP
      shell: echo 'export FLASK_APP=jmstudios_backend' >> ~/.bash_profile

    - name: run flask backend through uwsgi 
      become: true
      shell: cd jmstudios/backend/jmstudios_backend && uwsgi --socket 0.0.0.0:5050 --protocol=http -w wsgi
      async: 15770000
      poll: 0
