
---

- hosts: all
  tasks:
    - name: create venv
      shell: python3 -m venv /home/ubuntu/jmstudios/backend/venv

    - name: create alias for python3
      shell: alias python=python3

    - name: move to backend and pip install dependencies
      shell: cd jmstudios/backend && pip3 install -r requirements.txt
      become: true




- hosts: all
  vars:
    aws_url: '34.214.108.165'
  tasks:
    - name: send setup_data
      shell: scp -r -i ~/.ssh/latest_jrich_key ~/Documents/WebDevWorkspace/ReactPractice/ReactPractice/backend/jmstudios_backend/db_setup_scripts/setup_data 34.214.108.165:/jmstudios/backend/jmstudios_backend/db_setup_scripts/

    - name: send .aws credentials
      shell: scp -r -i ~/.ssh/latest_jrich_key ~/.aws 34.214.108.165:~/ 




- hosts: all
  tasks:
    - name: create flask env for flask modules
      shell: cd jmstudios/backend && pip3 install -e .
      become: true

    - name: export FLASK_APP
      shell: echo 'export FLASK_APP=jmstudios_backend' >> ~/.bash_profile

    - name: run flask backend through uwsgi 
      become: true
      shell: cd jmstudios/backend/jmstudios_backend && uwsgi --socket 0.0.0.0:5050 --protocol=http -w wsgi
      async: 15770000
      poll: 0
