
---

- hosts: all
  tasks:
    - name: move nginx to right location
      shell: mv jmstudios/nginx/nginx.conf /etc/nginx/
      become: true

    - name: run nginx test 
      shell: nginx -t
      become: true

    - name: start nginx
      become: true
      async: 15770000
      poll: 0
      service:
        name: nginx
        state: restarted

