
---

- hosts: all
  vars:
    machine_ip: "{{ machine_ip }}"
  tasks:
    - name: show me ip
      debug: 
        msg: "machine ip is {{machine_ip}}"
    - name: move nginx to right location
      shell: cp jmstudios/nginx/nginx.conf /etc/nginx/
      become: true

    - name: run nginx test 
      shell: nginx -t
      become: true

    - name: start nginx
      become: true
      async: 15770000
      poll: 0
      service:
        name: nginx
        state: restarted

