- hosts: all
  tasks:
    - name: install postgresql
      shell: apt-get install -y postgresql postgresql-contrib python3-dev python3-psycopg2 libpq-dev
      become: true
    - name: start postgresql
      shell: service postgresql start
      become: true
    - name: handle postgres initializations create role and database
      shell: createuser -s jmstudios && createdb -O jmstudios jmstudios
      become_user: postgres
