- hosts: all
  tasks:
    - name: packages for postgresql and ansible setup
      become: true
      apt: name={{ item }} state=latest
      with_items:
        - libpq-dev
        - python-psycopg2
        - postgresql
        - postgresql-contrib
        - python3-dev
        - python3-psycopg2

    - name: start postgresql
      become: true
      service:
        name: postgresql
        state: restarted

    - name: create user jmstudios
      become: true
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_user: 
        name: jmstudios
        password: jmstudios
        state: present
        role_attr_flags: SUPERUSER

    - name: create db
      become: true
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_db: 
        name: jmstudios
        encoding: UTF-8
        state: present
        owner: jmstudios
