- hosts: all
  tasks:
    - name: make sure the python psycopg2 is in
      become: true
      apt: name={{ item }} state=latest
      with_items:
        - libpq-dev
        - python-psycopg2

    - name: debug postgresql_user
      debug: msg="starting the create user"
    
    - name: create db user jmstudios
      become: true
      postgresql_user: 
        name: jmustudios
        password: jmstudios
        state: present
        role_attr_flags: SUPERUSER
        db: jmstudios

    - name: debug postgresql_db
      debug: msg="starting the create db"
    - name: create db
      become: true
      postgresql_db: 
        name: jmstudios
        encoding: UTF-8
        state: present
        login_user: jmstudios
