---
- hosts: all
  vars:
    machine_ip: "{{ machine_ip }}"
  tasks:
    - name: show me ip
      debug: 
        msg: "machine ip is {{machine_ip}}"
    - name: create project config
      shell: echo "const projectConfig = {" > jmstudios/project.config.ts
    - name: add machine ip
      shell: echo "'baseURL':" "'{{ machine_ip }}'" >> jmstudios/project.config.ts
    - name: close projectConfig
      shell: echo "}" >> jmstudios/project.config.ts
    - name: export projectConfig
      shell: echo "export default projectConfig" >> jmstudios/project.config.ts

- hosts: all
  tasks:
    - name: move to frontend project and install dependencies
      command: npm install --save
      args:
        chdir: jmstudios/
    - name: run build
      command: npm run build
      args:
        chdir: jmstudios/
    - name: run project 
      command: node server.js
      args:
        chdir: jmstudios/
      async: 15770000
      poll: 0
