- hosts: all
  tasks:
    - name: python setup libs
      become: true
      apt: name={{ item }} state=latest
      with_items:
        - python3-pip
        - python3.4-venv
        - libffi-dev
        - python3-setuptools
