- hosts: all
  tasks:
    - name: install system setup for project
      become: true
      apt: name={{ item }} state=latest update_cache=true
      with_items:
        - git
        - build-essential
        - libssl-dev
        - nodejs
        - node
        - nginx

    - name: install node
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - name: setup redirect 
      shell: sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
