- hosts: all
  tasks:
    - name: install git
      shell: apt-get update -y && apt-get install git -y && apt-get install build-essential libssl-dev -y 
    - name: install node
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - name: setup redirect 
      shell: sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
    - name: apt get install for node
      shell: apt-get install node -y && apt-get install -y nodejs
    - name: install python3 setup tools
      shell: apt-get install -y python3-setuptools
    - name: fix libs
      shell: apt-get install libffi-dev
    - name: install python3 venv creator
      shell: apt-get install -y python3.4-venv
    - name: install pip3
      shell: apt-get install -y python3-pip
    - name: install nginx
      shell: apt-get -y install nginx
    - name: install postgresql
      shell: apt-get install -y postgresql postgresql-contrib python3-dev python3-psycopg2 libpq-dev
    - name: start postgresql
      shell: service postgresql start
