- hosts: all
  tasks:
    - name: get git guud
      shell: apt-get update -y && apt-get install git -y 
    - name: get nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
