- hosts: all
  tasks:
    - name: Get base setup for git and python
      shell: apt-get update && apt-get install -y git &&  apt-get install -y build-essential git libjpeg-dev
    - name: clone backend
      git:
        repo: git@github.com:Distribute-Inc/backend_api.git
        dest: ~/backend_api
        accept_hostkey: true
        version: development
        update: no
