- hosts: all
  tasks:
    - name: clone backend
      git:
        repo: git@github.com:Distribute-Inc/backend_api.git
        dest: ~/backend_api
        accept_hostkey: true
        version: development
        update: no
