---

- hosts: all
  tasks:
    - name: clean dir
      become: true
      file:
        path: jmstudios
        state: absent
    - name: make jmstudios dir
      file:
        path: jmstudios
        state: directory

    - name: clone backend
      git:
        repo: 'https://github.com/JMStudiosJoe/ReactPractice'
        dest: ~/jmstudios
        version: 'JMStudiosBackend'
