---

- hosts: all
  tasks:
    - name: clean dir
      shell: rm -rf jmstudios
    - name: make jmstudios dir
      shell: mkdir jmstudios
    - name: clone backend
      git:
        repo: 'https://github.com/JMStudiosJoe/ReactPractice'
        dest: ~/jmstudios
