---

- hosts: all
  tasks:
    - name: clone backend
      git:
        repo: git@github.com:JMStudiosJoe/ReactPractice.git
        dest: ~/jmstudios
        accept_hostkey: true
        version: JMStudiosReact
        update: yes
